### ISSUE TITLE
OK to use your search API in other projects?

### ISSUE THREAD

**Issue by ludwigschubert** [karthikv/coursory#3]
Hi @karthikv, I'm experimenting with the exploreCourses API myself and am struggling with performance… would you mind if I use `coursory.com`'s search API for now? If traffic should ever get an issue I could set up my own instance of your backend.
It's just so much more performant than explorecourses directly. And it gives me JSON! \o/

**Comment by karthikv** [comment]
Feel free to make requests to it (so long as they don't put a large load on my server). One caveat is that the courses are a few years old. As per #2, the ExploreCourses API changed, and I can no longer extract section information (times a course is held) from it.

**Comment by ludwigschubert** [comment]
Aww, thanks, but that's unfortunate. :/
If I end up modifying your code to work with the new format, I'll let you know!
